services:


  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env

  mail-service:
    build: ./mail-service
    ports:
      - "8080:8080"
    volumes:
      - ./mail-service/data:/app/data
      - ./mail-service/token:/app/token
      - ./mail-service/credentials.json:/app/credentials.json
    environment:
      - GIN_MODE=release
